os: linux
language: node_js
notifications:
  email: false
node_js:
  - 12
  - 11
  - 10
  - 8
services:
  - docker
before_install:
  - docker-compose up -d
jobs:
  include:
    - stage: test
      script: yarn test
    # - stage: coverage
    #   script: yarn test:coverage
