version: '3'
services:
    mongodb:
        image: 'bitnami/mongodb:4.2'
        ports:
            - '27017:27017'
        volumes:
            - 'mongodb_data:/bitnami'

volumes:
    mongodb_data:
        driver: local
